global:
  helmDefault: false
  defaultValueFiles:
    - values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      name: default
    source:
      repoURL: https://gitlab.com/lappis-unb/gest-odadosipea/infra-lappis-ipea.git
      targetRevision: HEAD

argocdApplications:
  cert-manager:
    name: cert-manager
    namespace: cert-manager
    disableAutomated: false
    disable: false
    path: cert-manager
    targetRevision: HEAD
    helm: true

  superset:
    name: superset
    namespace: superset
    disableAutomated: false
    disable: false
    path: superset
    targetRevision: HEAD
    helm: true

  ingress-nginx:
    name: ingress-nginx
    namespace: ingress-nginx
    disableAutomated: false
    disable: false
    path: ingress-nginx
    targetRevision: HEAD
    helm: true

  keda:
    name: keda
    namespace: keda
    disableAutomated: false
    disable: false
    path: keda
    targetRevision: HEAD
    helm: true

  kube-prometheus-stack:
    name: kube-prometheus-stack
    namespace: monitoring
    disableAutomated: false
    disable: false
    path: kube-prometheus-stack
    targetRevision: HEAD
    helm: true

  longhorn:
    name: longhorn
    namespace: longhorn-system
    disableAutomated: false
    disable: false
    path: longhorn
    targetRevision: HEAD
    helm: true

  minio:
    name: minio
    namespace: minio
    disableAutomated: false
    disable: false
    path: minio
    targetRevision: HEAD
    helm: true

  jupyterhub:
    name: jupyterhub
    namespace: jupyterhub
    disableAutomated: false
    disable: false
    path: jupyterhub/homolog

  # TODO: adicionar instalacoes q precisam de kustomize (airflow, jupyterhub, kube-vip)

